apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-rc
spec:
  replicas: 2
  selector:
    app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers: jenkins
      - name:
        image: saranam/karthik:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: jenkins
