apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-rc
spec:
  replicas: 2
  selector:
    app: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-pod
        image: saranam/karthik:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-rc
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 8080

